### ISSUE TITLE
IT HAS BEEN FIGURED OUT!

### ISSUE THREAD

**Issue by ShakeAndWiggle20** [sqdldev/countdown-arg-tool#2]
[@MuhammadTheOld](https://www.youtube.com/@MuhammadTheOld) on Youtube figured it out!
the title says "answer"
each number corresponds to the morse code in the description of each number
it says:
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna

Thank you for creating the tool and I hope next year countdown will return...

**Comment by whimsicalweasel52** [comment]
Hello, thank you for your concern, but I have already been working on an update at this moment.
